---
- name: executing multiple playbooks
  hosts: all
  tasks:
    - name: installing tmux
      apt:
        name: tmux
        state: present

    - name: create an archive
      archive:
        path: /var/log
        dest: /tmp/harsh.tar.gz
        format: gz


- name: second play
  hosts: all
  tasks:
    - name: installing git
      apt:
        name: git
        state: present

